INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ajax', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Amherstburg', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arnprior', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aurora', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aylmer', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Barrie', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Belleville', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bradford West Gwillimbury', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brampton', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brantford', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brockville', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Burlington', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cambridge', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carleton Place', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cobourg', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Collingwood', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cornwall', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dryden', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Erie', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Frances', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gananoque', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Georgina', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Goderich', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grimsby', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Guelph', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Halton Hills', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hamilton', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hanover', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hawkesbury', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ingersoll', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Innisfil', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kingston', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kitchener', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LaSalle', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lincoln', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('London', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Markham', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Midland', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Milton', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mississauga', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('New Tecumseth', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Newmarket', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Niagara Falls', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Niagara-on-the-Lake', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('North Bay', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oakville', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Orangeville', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Orillia', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oshawa', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ottawa', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Owen Sound', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Parry Sound', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pelham', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pembroke', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Penetanguishene', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Perth', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Peterborough', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Petrolia', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pickering', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Port Colborne', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Renfrew', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Richmond Hill', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sarnia', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sault Ste. Marie', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shelburne', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Smiths Falls', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Catharines', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Marys', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Thomas', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stratford', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tecumseh', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Thorold', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Thunder Bay', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tillsonburg', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Toronto', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vaughan', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wasaga Beach', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waterloo', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Welland', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Whitby', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Whitchurch-Stouffville', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Windsor', true, 9);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Woodstock', true, 9);
