INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arctic Bay', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arviat', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Baker Lake', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cambridge Bay', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cape Dorset', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chesterfield Inlet', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Clyde River', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Coral Harbour', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gjoa Haven', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grise Fiord', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hall Beach', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Igloolik', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Iqaluit', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kimmirut', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kugaaruk', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kugluktuk', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nanisivik', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pangnirtung', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Polaris', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pond Inlet', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Qikiqtarjuaq', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rankin Inlet', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Repulse Bay', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Resolute', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sanikiluaq', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Taloyoak', true, 8);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Whale Cove', true, 8);
