INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Abbotsford', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aldergrove', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aldergrove', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Armstrong', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ashcroft', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Blind Bay', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Burns Lake', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cache Creek', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Campbell River', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Castlegar', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chase', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chemainus', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chetwynd', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chilliwack', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Courtenay', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cowichan Bay', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cranbrook', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Creston', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Crofton', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cultus Lake', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cumberland', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dallas', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dawson Creek', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Deep Cove', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Duck Lake', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Duncan', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elkford', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Enderby', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fernie', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Nelson', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort St. James', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort St. John', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fraser Lake', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fruitvale', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gibsons', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gold River', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Golden', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grand Forks', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Harrison Hot Springs', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hope', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Houston', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Invermere', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kamloops', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kelowna', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kent', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kimberley', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kitimat', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ladysmith', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lake Cowichan', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lillooet', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lions Bay', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Logan Lake', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lumby', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mackenzie', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Merritt', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mill Bay', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Miller\'s Landing', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nakusp', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nanaimo', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nelson', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oliver', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('One Hundred Mile House', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Osoyoos', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Parksville', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pemberton', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Penticton', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Port Alberni', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Port Hardy', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Port McNeill', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Powell River', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Prince George', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Prince Rupert', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Princeton', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Quesnel', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Revelstoke', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Roberts Creek', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rossland', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Salmo', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Salmon Arm', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sechelt', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shawnigan', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sicamous', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Smithers', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sooke', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sparwood', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Squamish', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Summerland', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Terrace', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Trail', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tumbler Ridge', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ucluelet', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vancouver', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vanderhoof', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vernon', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Victoria', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Walnut Grove', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Welcome Beach', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Whistler', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('White Rock', true, 2);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Williams Lake', true, 2);
