INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bathurst', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Blackville', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Boiestown', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bristol', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cambridge-Narrows', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Campbellton', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Canterbury', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chipman', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Colpitts Settlement', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dalhousie', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Doaktown', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Edmundston', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fredericton', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grand Manan', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grand-Sault/Grand Falls', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hampton', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hartland', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Harvey Station', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hillsborough', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hoyt', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('McAdam', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Minto', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Miramichi', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Moncton', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nackawic', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Northampton', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Old Ridge', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oromocto', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Perth-Andover', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Petitcodiac', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Plaster Rock', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rexton', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Riverview', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rothesay', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sackville', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint John', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Salisbury', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Springfield,Kings County', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Andrews', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. George', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stanley', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sunny Corner', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sussex', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wilsons Beach', true, 4);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Woodstock', true, 4);
