INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aklavik', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Colville Lake', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Deline', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Enterprise', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Good Hope', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Liard', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Mcpherson', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Providence', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Resolution', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Simpson', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Smith', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hay River', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Holman', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Inuvik', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lutselk\'E', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Norman Wells', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Paulatuk', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rae Edzo', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rae Lakes', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sachs Harbour', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Trout Lake', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tsiigehtchic', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tuktoyaktuk', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tulita', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wekweti', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wha Ti', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wrigley', true, 6);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Yellowknife', true, 6);
