INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Airdrie', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Athabasca', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Banff', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bragg Creek', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brooks', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Calgary', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Canmore', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Clairmont', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Claresholm', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cochrane', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cold Lake', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Drayton Valley', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Drumheller', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Edmonton', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Edson', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Assiniboine', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort McMurray', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fort Saskatchewan', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grande Cache', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grande Prairie', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hanna', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('High Level', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('High River', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hinton', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Irricana', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Jasper', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kananaskis Village', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lacombe', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lake Louise', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leduc', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lloydminster', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lethbridge', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Medicine Hat', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nisku', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nordegg', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Okotoks', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Olds', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Peace River', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pincher Creek', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Red Deer', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rocky Mountain House', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sherwood Park', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Slave Lake', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Albert', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Paul', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stettler', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stony Plain', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Strathmore', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Taber', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Three Hills', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tignish', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vermilion', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waterton Lakes', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wetaskiwin', true, 1);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Whitecourt', true, 1);
