INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arnold\'s Cove', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Avondale', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Baie Verte', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bay Roberts', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beaumont', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bell Island', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bishop\'s Falls', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Black Tickle', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Blaketown', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bonavista', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Botwood', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Buchans', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Burgeo', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Burnt Islands', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carbonear', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carmanville', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cartwright', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Change Islands', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Channel-Port aux Basques', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Charlottetown, LAB', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Churchill Falls', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Clarenville', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Conception Bay South (Foxtrap)', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Conception Bay South (Manuels)', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Conche', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Conne River', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cook\'s Harbour', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Corner Brook', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cow Head', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Croque', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Daniel\'s Harbour', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Deer Lake', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Eastport', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('English Harbour West', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ferryland', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Flower\'s Cove', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fogo Island', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Forteau', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gambo', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gander', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gaultois', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glenwood', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glovertown', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grand Bank', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grand Falls-Windsor', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grey River', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hampden', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Happy Valley-Goose Bay', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Harbour Breton', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hare Bay', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hermitage', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hopedale', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('King\'s Cove', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('King\'s Point', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('La Scie', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Labrador City', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lamaline', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lark Harbour', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lawn', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lethbridge', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lewisporte', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Little Heart\'s Ease', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Main Brook', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Makkovik', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mary\'s Harbour', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Marystown', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('McCallum', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('McKay\'s', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Meadows', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Middle Arm', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Milltown', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mobile', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mount Carmel', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mount Pearl', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Musgrave Harbour', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nain', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Norman Bay', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('North West River', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Old Perlican', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pasadena', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Piccadilly', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pilley\'s Island', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Placentia', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Plum Point', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Point Leamington', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pollard\'s Point', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Port Hope Simpson', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Port Rexton', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Port Saunders', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Postville', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ramea', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Random Island', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Red Bay', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rencontre East', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rigolet', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rocky Harbour', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Roddickton', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rushoon', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sheshashit', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Springdale', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St John\'s', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Anthony', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Bernard\'s-Jacques Fontaine', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Brendan\'s', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Brides', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. George\'s', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. John\'s', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. John\'s (Goulds)', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Lawrence', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Lewis', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Lunaire', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Mary\'s', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stephenville', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Summerford', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Swift Current', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Terrenceville', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Torbay', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Trepassey', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Trout River', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Twillingate', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Upper Ferry', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wesleyville', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('West St. Modeste', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Westport', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wing\'s Point', true, 5);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Woody Point', true, 5);
