INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Alexander', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Altona', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Anola', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arborg', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Argyle', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arnaud', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ashern', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Austin', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Baldur', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Balmoral', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beausejour', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beulah', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Birtle', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Boissevain', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brandon', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brookdale', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Camperville', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carberry', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carman', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cartwright', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Churchill', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cranberry Portage', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cross Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cypress River', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dakota Tipi', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dauphin', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Decker', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Deloraine', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dominion City', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Douglas', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dugald', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Easterville', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ebb And Flow', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elie', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elkhorn', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elm Creek', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Erickson', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ethelbert', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fairford', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fisher Branch', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Flin Flon', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Forrest', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gilbert Plains', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gillam', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gimli', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gladstone', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glenboro', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grand Rapids', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grandview', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gretna', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Griswold', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grosse Isle', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grunthal', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hamiota', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hartney', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hodgson', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Holland', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Île Des Chênes', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Inwood', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Island Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Justice', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Killarney', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Koostatak', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('La Broquerie', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lac Brochet', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lac Du Bonnet', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Landmark', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Langruth', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lauder', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Laurier', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leaf Rapids', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lorette', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lundar', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lynn Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Macgregor', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Manitou', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Margaret', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Marius', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Melita', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Miami', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Minnedosa', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Morden', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Morris', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('N.-D.-De-Lourdes', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Neepawa', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nelson House', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Niverville', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Norway House', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('O\'Hanley', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oak River', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oakbank', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Opaskwayak', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oxford House', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Peguis First Nation', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pelican Rapids', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Petersfield', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pierson', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pilot Mound', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pinawa', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pine Falls', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Piney', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pipestone', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Plum Coulee', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Poplarfield', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Portage', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Portage La Prairie', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Powerview', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pukatawagan', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Red Sucker Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Reston', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('River Hills', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rivers', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Riverton', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Roblin', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rorketon', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rosenort', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rossburn', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rosser', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Russell', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Boniface', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Claude', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Georges', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Jean-Baptiste', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Laurent', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Lazare', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Pierre-Jolys', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sainte-Anne', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sanford', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Scanterbury', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Selkirk', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shoal Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Snow Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Somerset', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Souris', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sperling', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Split Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sprague', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Claude', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Laurent', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Norbert', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Pierre-Jolys', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Theresa Point', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Starbuck', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ste Anne', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ste. Agathe', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ste. Anne', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Steinbach', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stonewall', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Strathclair', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Swan Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Swan River', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tadoule Lake', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Teulon', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('The Pas', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Thompson', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tourond', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Treherne', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Virden', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vita', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waasagomach', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wabowden', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wanipigow', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Warren', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waskada', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wawanesa', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waywayseecappo', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Whitemouth', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Winkler', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Winnipeg', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Winnipegosis', true, 3);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Scholarships', true, 3);
