INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('ADVOCATE HARBOUR', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('AMHERST', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('ANNAPOLIS ROYAL', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('ANTIGONISH', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('ARICHAT', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('AUBURN', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('BADDECK', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('BARRINGTON PASSAGE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('BEDFORD', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('BLOCKHOUSE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('BRIDGETOWN', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('BRIDGEWATER', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('BROOKFIELD', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('CALEDONIA', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('CAMBRIDGE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('CANNING', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('CANSO', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('CHESTER BASIN', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('CHETICAMP', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('COLE HARBOUR', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('COXHEATH', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('DARTMOUTH', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('DARTMOUTH', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('DIGBY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('ELMSDALE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('FALL RIVER', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('FREEPORT', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('GLACE BAY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('GLENWOOD', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('GREENWOOD', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('GUYSBOROUGH', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('HALIFAX', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('INVERNESS', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('IONA', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('KENNETCOOK', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LABUTTE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LAWRENCETOWN', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LIVERPOOL', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LOCKEPORT', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LOUISDALE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LR SACKVILLE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('LUNENBURG', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MABOU', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MAHONE BAY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MARGAREE HARBOUR', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MIDDLE MUSQUODOBOIT', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MIDDLETON', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MILFORD STATION', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MONASTERY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('MUSQUODOBOIT HBR', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('NEIL\'S HARBOUR', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('NEW GERMANY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('NEW GLASGOW', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('NEW MINAS', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('NEW WATERFORD', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('OXFORD', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('PARRSBORO', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('PICTOU', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('POMQUET', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('PORT HAWKESBURY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('PUGWASH', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('RIVER HEBERT', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('SHEET HARBOUR', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('SHELBURNE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('SHERBROOKE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('SPRINGHILL', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('SYDNEY MINES', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('SYDNEY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('SYDNEY', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('TATAMAGOUCHE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('TRURO', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('TUSKET', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('UPPER TANTALLON', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('WESTVILLE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('WEYMOUTH', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('WINDSOR', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('WOLFVILLE', true, 7);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('YARMOUTH', true, 7);
