INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Abbey', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aberdeen', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Abernethy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Admiral', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Air Ronge', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Alameda', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Albertville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Alida', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Allan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Alsask', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Alvena', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aneroid', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Annaheim', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Antler', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arborfield', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Archerwill', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arcola', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ardath', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ardill', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arelee', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Arran', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Asquith', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Assiniboia', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Atwater', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Avonhurst', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Avonlea', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aylesbury', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Aylsham', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Balcarres', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Balgonie', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bangor', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bankend', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Battleford', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beatty', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beaubier', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beauval', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beechy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Belle Plaine', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bellegarde', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bengough', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Benson', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bethune', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bienfait', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Big Beaver', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Big River', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Biggar', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Birch Hills', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Birsay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bjorkdale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Black Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bladworth', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Blaine Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Blumenhof', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Borden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bracken', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bradwell', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bredenbury', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Briercrest', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Broadview', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brock', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Broderick', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bromhead', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brooksby', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brownlee', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bruno', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Buchanan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Buena Vista', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Buffalo Narrows', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bulyea', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Burr', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Burstall', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Bushell Park', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cabri', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cadillac', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Calder', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Candiac', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Candle Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cando', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Canoe Narrows', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Canora', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Canwood', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carievale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carlyle', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carmel', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carnduff', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Caronport', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Caron', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carragana', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Carrot River', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('CasaRio', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Central Butte', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ceylon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chamberlain', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chaplin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chelan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chitek Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Choiceland', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Christopher Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Churchbridge', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Clair', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Clavet', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Clearwater River', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Climax', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cochin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Coderre', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Codette', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cole Bay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Coleville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Colonsay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Congress', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Conquest', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Consul', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Coppersands', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Corman Park', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Corning', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Coronach', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cowessess', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Craik', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Crane Valley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Craven', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Creelman', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Creighton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Crooked River', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Crystal Springs', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cudworth', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cumberland House', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cupar', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cut Knife', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cymric', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('D\'Arcy Station', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dafoe', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dalmeny', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Danbury', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Davidson', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Debden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Deer Valley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Delisle', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Delmas', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Demaine', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Denare Beach', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Denholm', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Denzil', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Deschambault Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dilke', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dillon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dinsmore', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dodsland', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dollard', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Domremy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dorintosh', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Drake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Drinkwater', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dubuc', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Duck Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dundurn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Duval', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dysart', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Earl Grey', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Eastend', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Eatonia', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ebenezer', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Edam', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Edenwold', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Edgeley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elbow', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elfros', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elrose', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Elstow', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Emerald Park', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Endeavour', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Englefeld', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ernfold', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Esterhazy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Estevan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Eston', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Eyebrow', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fairlight', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fairy Glen', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fenwood', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ferland', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fife Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fillmore', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Findlater', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fiske', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Flaxcombe', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fleming', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Flintoft', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('FoamLake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fond DuLac', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Forget', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('FortQu\' Appelle', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fosston', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fox Valley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Francis', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Frenchman Butte', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Frobisher', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Frontier', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Fulda', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Furdale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gainsborough', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gallivan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Garrick', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gerald', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gladmar', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glaslyn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glen Ewen', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glenavon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glenbain', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glenbush', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glenside', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glentworth', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Glidden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Golden Prairie', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Goodeve', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Goodsoil', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Govan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grandora', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grasswood', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gravelbourg', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grayson', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gray', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Green Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Grenfell', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Griffin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gronlid', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Guernsey', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gull Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hafford', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hagen', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hague', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Halbrite', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Handel', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hanley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Harris', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hawarden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hazel Dell', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hazenmore', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hazlet', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hendon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Henribourg', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hepburn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Herbert', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Herschel', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Heward', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hodgeville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hoey', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Holbein', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Holdfast', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Homefield', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hoosier', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hudson Bay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Humboldt', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hyas', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ile-A-La-Crosse', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Imperial', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('IndianHead', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Invermay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ituna', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Jackfish Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Jansen', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kamsack', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kayville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Keeler', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kelfield', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kelliher', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kelso', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kelvington', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kenaston', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kendal', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kennedy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kenosee Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kerrobert', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Killaly', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kincaid', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kindersley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kinistino', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kinoosao', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kipling', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kisbey', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kronau', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Krydor', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kuroki', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Kyle', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('La Loche', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('La Ronge', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lac Vert', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lafleche', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Laird', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lake Alma', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lake Lenore', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lampman', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lancer', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Landis', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Langbank', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Langenburg', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Langham', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lang', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lanigan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lashburn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leader', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leask', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lebret', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lemberg', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leoville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leross', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leroy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Leslie', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lestock', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lewvan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Liberty', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Liebenthal', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Limerick', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lintlaw', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lipton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Livelong', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lloydminster', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lone Rock', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Loon Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Loreburn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Loverna', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Love', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lucky Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Lumsden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Luseland', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Macdowall', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Macklin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Macnutt', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Macoun', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Macrorie', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Maidstone', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Major', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Makwa', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mankota', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Manor', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mantario', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Maple Creek', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Marcelin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Marengo', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Margo', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Markinch', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Marquis', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Marsden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Marshall', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Martensville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Maryfield', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mayfair', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Maymont', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mazenod', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mccord', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mckague', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mclean', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mcmahon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Meacham', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Meadow Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Meath Park', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Medstead', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Melfort', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Melville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mendham', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Meota', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mervin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Meskanaw', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Meyronne', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Midale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Middle Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mikado', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Milden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mildred', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Milestone', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Minton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mistatim', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mont Nebo', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Montmartre', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Montreal Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Moose Jaw', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Moosomin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Morse', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mortlach', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mossbank', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mozart', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Muenster', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Muskoday', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Naicam', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Neidpath', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Neilburg', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Netherhill', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Neudorf', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Neville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nipawin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nokomis', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Norquay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('North Battleford', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('North Portal', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('North Weyburn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Northgate', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Nut Mountain', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Odessa', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ogema', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Okla', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Onion Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Orkney', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ormiston', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Osage', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Osler', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oungre', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Outlook', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Oxbow', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Paddockwood', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pakwaw Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pambrun', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pangman', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Paradise Hill', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Parkside', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Parry', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Patuanak', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Paynton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Peebles', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pelican Narrows', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pelly', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pennant Station', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pense', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Perdue', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Piapot', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pierceland', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pilger', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pilot Butte', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pinehouse Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Plato', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pleasantdale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Plenty', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Plunkett', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ponteix', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Porcupine Plain', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Prairie River', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Preeceville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Prelate', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Prince Albert', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Prud\' Homme', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Punnichy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Qu\'Appelle', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Quill Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Quinton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rabbit Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Radisson', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Radville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rama', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rapid View', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Raymore', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Red Earth', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Redvers', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Regina Beach', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Regina', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rhein', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Riceton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Richardson', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Richmound', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ridgedale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Riverhurst', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Riverside Estates', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Robsart', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rocanville', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rockglen', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rockhaven', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rokeby', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rose Valley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rosetown', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rosthern', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rouleau', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saltcoats', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sandy Bay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saskatoon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sceptre', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Scott', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Scout Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sedley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Semans', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Senlac', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shamrock', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shaunavon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sheho', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shell Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shellbrook', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shipman', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Silton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Simmie', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Simpson', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sintaluta', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Smeaton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Smiley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Snowden', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sonningdale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Southend', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Southey', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sovereign', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Spalding', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Speers', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Spiritwood', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Spring Valley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Springside', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Spruce Home', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Spruce Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Spy Hill', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Benedict', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Brieux', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Denis', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Gregor', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St IsidoreDeBellevue', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Louis', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Walburg', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stanley Mission', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Star City', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Steelman', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stenen', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stewart Valley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stockholm', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stony Rapids', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Storthoaks', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Stoughton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Strasbourg', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Strongfield', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sturgeon Landing', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sturgis', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Success', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Swift Current', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sylvania', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tantallon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tessier', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Theodore', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Timber Bay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tisdale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Togo', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tompkins', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Torquay', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tramping Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tribune', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Trossachs', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tuffnell', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tugaske', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Turnor Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Turtleford', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tuxford', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tyner', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tyvan', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Unity', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Uranium City', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('ValMarie', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vanguard', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vanscoy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vawn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Verigin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Verwood', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vibank', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Viceroy', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Victoire', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vidora', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Viscount', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vonda', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wadena', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wakaw', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waldeck', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waldheim', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wapella', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Warman', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waseca', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waskesiu Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Waterhen Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Watrous', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Watson', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wauchope', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wawota', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Webb', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Weekes', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Weirdale', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Weldon', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Welwyn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Weyakwin', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Weyburn', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('White Bear', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('White City', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('White Fox', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Whitewood', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wilcox', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wilkie', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Willow Bunch', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Willowbrook', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Windthorst', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wiseton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wishart', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wollaston Lake', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wolseley', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('WoodMountain', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Woodrow', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wroxton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wymark', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Wynyard', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Yarbo', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Yellow Creek', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Yellow Grass', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Yorkton', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Young', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Zealandia', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Zehner', true, 12);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('ZenonPark', true, 12);
