INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Alma', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ancienne Lorette', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Anjou', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Baie Comeau', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Baie-Saint-Paul', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beauport', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Beaupre', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Becancour', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Berthierville', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Blainville', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Boucherville', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Brossard', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chevery', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Chicoutimi', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Cowansville', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Dorval', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Drummondville', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Forestville', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gaspe', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Gatineau', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Hull', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Jonquiere', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('La Malbaie', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Laval', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Levis', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Longueuil', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Magog', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Matane', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Métis-Sur-Mer', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mont Laurier', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Mont Tremblant', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Montebello', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Montreal', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Natashquan', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Orford', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Perce', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Petite Rivière St-François', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Pointe Claire', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Quebec City', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rimouski', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Riviere Du Loup', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Roberval', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rock Forest', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Rouyn Noranda', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Saint-Joseph-de-la-Rive', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sainte Catherine', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sainte-Adele', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sainte-Foy', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sept-Îles', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Shawinigan', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Sherbrooke', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Jerome', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Jovite', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St Laurent', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St-sauveur', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Georges De Beauce', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Jean-Sur-Richelieu', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('St. Liboire', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ste Anne De Beaupre', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Ste-helene-de-bagot', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Tadoussac', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Thetford Mines', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Trois Rivières', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Val D\'or', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Val-des-Lacs', true, 11);
INSERT INTO city(`city_name`, `isActive`, `provance_provance_id`) VALUES('Vaudreuil', true, 11);
