insert into street (street_name, isActive) values ('Marcy', true);
insert into street (street_name, isActive) values ('Drewry', false);
insert into street (street_name, isActive) values ('Manitowish', true);
insert into street (street_name, isActive) values ('Luster', true);
insert into street (street_name, isActive) values ('Norway Maple', false);
insert into street (street_name, isActive) values ('Warner', true);
insert into street (street_name, isActive) values ('Gulseth', false);
insert into street (street_name, isActive) values ('Forster', false);
insert into street (street_name, isActive) values ('Reinke', false);
insert into street (street_name, isActive) values ('8th', true);
insert into street (street_name, isActive) values ('Pepper Wood', true);
insert into street (street_name, isActive) values ('Southridge', false);
insert into street (street_name, isActive) values ('Summit', false);
insert into street (street_name, isActive) values ('Harper', false);
insert into street (street_name, isActive) values ('Elka', true);
insert into street (street_name, isActive) values ('Westport', false);
insert into street (street_name, isActive) values ('Golf Course', false);
insert into street (street_name, isActive) values ('Novick', true);
insert into street (street_name, isActive) values ('1st', false);
insert into street (street_name, isActive) values ('Thompson', false);
insert into street (street_name, isActive) values ('Donald', true);
insert into street (street_name, isActive) values ('Paget', false);
insert into street (street_name, isActive) values ('Elka', true);
insert into street (street_name, isActive) values ('Bluestem', true);
insert into street (street_name, isActive) values ('Briar Crest', false);
insert into street (street_name, isActive) values ('Fulton', false);
insert into street (street_name, isActive) values ('Fairfield', true);
insert into street (street_name, isActive) values ('Esker', false);
insert into street (street_name, isActive) values ('Golden Leaf', true);
insert into street (street_name, isActive) values ('Monument', false);
insert into street (street_name, isActive) values ('Gateway', true);
insert into street (street_name, isActive) values ('Jackson', true);
insert into street (street_name, isActive) values ('Surrey', true);
insert into street (street_name, isActive) values ('Derek', true);
insert into street (street_name, isActive) values ('Eastlawn', true);
insert into street (street_name, isActive) values ('Clyde Gallagher', true);
insert into street (street_name, isActive) values ('Sachs', true);
insert into street (street_name, isActive) values ('Banding', false);
insert into street (street_name, isActive) values ('American Ash', false);
insert into street (street_name, isActive) values ('Lyons', true);
insert into street (street_name, isActive) values ('Main', false);
insert into street (street_name, isActive) values ('Red Cloud', false);
insert into street (street_name, isActive) values ('Independence', false);
insert into street (street_name, isActive) values ('Bobwhite', false);
insert into street (street_name, isActive) values ('Florence', true);
insert into street (street_name, isActive) values ('Gina', false);
insert into street (street_name, isActive) values ('Randy', true);
insert into street (street_name, isActive) values ('Monica', true);
insert into street (street_name, isActive) values ('Monica', false);
insert into street (street_name, isActive) values ('Green', false);
insert into street (street_name, isActive) values ('Barby', true);
insert into street (street_name, isActive) values ('Truax', true);
insert into street (street_name, isActive) values ('Helena', false);
insert into street (street_name, isActive) values ('Esker', false);
insert into street (street_name, isActive) values ('Sage', false);
insert into street (street_name, isActive) values ('Declaration', true);
insert into street (street_name, isActive) values ('Corry', false);
insert into street (street_name, isActive) values ('Rieder', true);
insert into street (street_name, isActive) values ('Grasskamp', true);
insert into street (street_name, isActive) values ('Texas', false);
insert into street (street_name, isActive) values ('Hauk', false);
insert into street (street_name, isActive) values ('Eagle Crest', true);
insert into street (street_name, isActive) values ('Birchwood', true);
insert into street (street_name, isActive) values ('Donald', false);
insert into street (street_name, isActive) values ('Clyde Gallagher', true);
insert into street (street_name, isActive) values ('Glendale', true);
insert into street (street_name, isActive) values ('Fuller', true);
insert into street (street_name, isActive) values ('Anthes', false);
insert into street (street_name, isActive) values ('Fisk', true);
insert into street (street_name, isActive) values ('Derek', true);
insert into street (street_name, isActive) values ('Nevada', false);
insert into street (street_name, isActive) values ('Schlimgen', false);
insert into street (street_name, isActive) values ('Sutteridge', false);
insert into street (street_name, isActive) values ('Welch', true);
insert into street (street_name, isActive) values ('Knutson', true);
insert into street (street_name, isActive) values ('Lakeland', true);
insert into street (street_name, isActive) values ('Sage', true);
insert into street (street_name, isActive) values ('Hazelcrest', false);
insert into street (street_name, isActive) values ('Loftsgordon', false);
insert into street (street_name, isActive) values ('Manley', true);
insert into street (street_name, isActive) values ('Algoma', false);
insert into street (street_name, isActive) values ('Brickson Park', false);
insert into street (street_name, isActive) values ('Harper', false);
insert into street (street_name, isActive) values ('Dunning', false);
insert into street (street_name, isActive) values ('Corscot', true);
insert into street (street_name, isActive) values ('Aberg', true);
insert into street (street_name, isActive) values ('Annamark', true);
insert into street (street_name, isActive) values ('8th', false);
insert into street (street_name, isActive) values ('Cordelia', false);
insert into street (street_name, isActive) values ('Vera', false);
insert into street (street_name, isActive) values ('West', false);
insert into street (street_name, isActive) values ('Delladonna', true);
insert into street (street_name, isActive) values ('David', true);
insert into street (street_name, isActive) values ('Parkside', false);
insert into street (street_name, isActive) values ('Mesta', false);
insert into street (street_name, isActive) values ('Stephen', false);
insert into street (street_name, isActive) values ('Orin', false);
insert into street (street_name, isActive) values ('Marcy', false);
insert into street (street_name, isActive) values ('Cardinal', false);
insert into street (street_name, isActive) values ('Luster', false);
insert into street (street_name, isActive) values ('Merrick', true);
insert into street (street_name, isActive) values ('American', false);
insert into street (street_name, isActive) values ('Rusk', false);
insert into street (street_name, isActive) values ('Monument', false);
insert into street (street_name, isActive) values ('Ruskin', true);
insert into street (street_name, isActive) values ('Village', false);
insert into street (street_name, isActive) values ('Hoard', true);
insert into street (street_name, isActive) values ('Magdeline', true);
insert into street (street_name, isActive) values ('Arizona', true);
insert into street (street_name, isActive) values ('Paget', false);
insert into street (street_name, isActive) values ('Dovetail', true);
insert into street (street_name, isActive) values ('Twin Pines', true);
insert into street (street_name, isActive) values ('Kropf', true);
insert into street (street_name, isActive) values ('Sunbrook', false);
insert into street (street_name, isActive) values ('Stang', false);
insert into street (street_name, isActive) values ('Springs', false);
insert into street (street_name, isActive) values ('Mandrake', true);
insert into street (street_name, isActive) values ('Susan', true);
insert into street (street_name, isActive) values ('Randy', true);
insert into street (street_name, isActive) values ('Mitchell', true);
insert into street (street_name, isActive) values ('Badeau', true);
insert into street (street_name, isActive) values ('Schmedeman', false);
insert into street (street_name, isActive) values ('Claremont', false);
insert into street (street_name, isActive) values ('Talisman', true);
insert into street (street_name, isActive) values ('Di Loreto', true);
insert into street (street_name, isActive) values ('Huxley', true);
insert into street (street_name, isActive) values ('Veith', true);
insert into street (street_name, isActive) values ('Clarendon', true);
insert into street (street_name, isActive) values ('Browning', true);
insert into street (street_name, isActive) values ('Havey', false);
insert into street (street_name, isActive) values ('Dwight', true);
insert into street (street_name, isActive) values ('Dottie', false);
insert into street (street_name, isActive) values ('Mosinee', false);
insert into street (street_name, isActive) values ('Macpherson', false);
insert into street (street_name, isActive) values ('Eggendart', true);
insert into street (street_name, isActive) values ('Anhalt', true);
insert into street (street_name, isActive) values ('Di Loreto', true);
insert into street (street_name, isActive) values ('Mifflin', false);
insert into street (street_name, isActive) values ('Harbort', false);
insert into street (street_name, isActive) values ('Magdeline', true);
insert into street (street_name, isActive) values ('Southridge', false);
insert into street (street_name, isActive) values ('Sunbrook', false);
insert into street (street_name, isActive) values ('Lien', true);
insert into street (street_name, isActive) values ('Old Gate', true);
insert into street (street_name, isActive) values ('Oak', false);
insert into street (street_name, isActive) values ('Heffernan', true);
insert into street (street_name, isActive) values ('Harper', false);
insert into street (street_name, isActive) values ('Pennsylvania', true);
insert into street (street_name, isActive) values ('Delladonna', false);
insert into street (street_name, isActive) values ('Meadow Ridge', false);
insert into street (street_name, isActive) values ('Bluejay', false);
insert into street (street_name, isActive) values ('Almo', true);
insert into street (street_name, isActive) values ('Emmet', false);
insert into street (street_name, isActive) values ('Nelson', false);
insert into street (street_name, isActive) values ('Hoepker', false);
insert into street (street_name, isActive) values ('Bultman', false);
insert into street (street_name, isActive) values ('Schurz', true);
insert into street (street_name, isActive) values ('Ridge Oak', false);
insert into street (street_name, isActive) values ('Warbler', true);
insert into street (street_name, isActive) values ('Ridgeview', false);
insert into street (street_name, isActive) values ('Oakridge', false);
insert into street (street_name, isActive) values ('Mitchell', true);
insert into street (street_name, isActive) values ('Waubesa', true);
insert into street (street_name, isActive) values ('Union', true);
insert into street (street_name, isActive) values ('Evergreen', true);
insert into street (street_name, isActive) values ('Schiller', false);
insert into street (street_name, isActive) values ('Lukken', true);
insert into street (street_name, isActive) values ('Kim', false);
insert into street (street_name, isActive) values ('Veith', true);
insert into street (street_name, isActive) values ('Longview', true);
insert into street (street_name, isActive) values ('Corry', true);
insert into street (street_name, isActive) values ('Maryland', false);
insert into street (street_name, isActive) values ('Badeau', true);
insert into street (street_name, isActive) values ('Lakewood', false);
insert into street (street_name, isActive) values ('Hanover', true);
insert into street (street_name, isActive) values ('Sauthoff', false);
insert into street (street_name, isActive) values ('Green Ridge', false);
insert into street (street_name, isActive) values ('Lien', true);
insert into street (street_name, isActive) values ('Oakridge', true);
insert into street (street_name, isActive) values ('Knutson', true);
insert into street (street_name, isActive) values ('Pankratz', false);
insert into street (street_name, isActive) values ('Butternut', false);
insert into street (street_name, isActive) values ('Fallview', false);
insert into street (street_name, isActive) values ('Westport', true);
insert into street (street_name, isActive) values ('Stang', true);
insert into street (street_name, isActive) values ('Dottie', false);
insert into street (street_name, isActive) values ('Sachs', true);
insert into street (street_name, isActive) values ('Macpherson', true);
insert into street (street_name, isActive) values ('Bartillon', true);
insert into street (street_name, isActive) values ('Briar Crest', false);
insert into street (street_name, isActive) values ('Golden Leaf', true);
insert into street (street_name, isActive) values ('Park Meadow', true);
insert into street (street_name, isActive) values ('Vera', true);
insert into street (street_name, isActive) values ('Bayside', true);
insert into street (street_name, isActive) values ('Bartillon', false);
insert into street (street_name, isActive) values ('1st', false);
insert into street (street_name, isActive) values ('Helena', true);
insert into street (street_name, isActive) values ('Ridgeway', true);
insert into street (street_name, isActive) values ('Maple', false);
insert into street (street_name, isActive) values ('Stang', false);
insert into street (street_name, isActive) values ('Hoffman', true);
insert into street (street_name, isActive) values ('Bunting', true);
insert into street (street_name, isActive) values ('Bowman', false);
insert into street (street_name, isActive) values ('Northport', false);
insert into street (street_name, isActive) values ('Eggendart', false);
insert into street (street_name, isActive) values ('Parkside', true);
insert into street (street_name, isActive) values ('Duke', true);
insert into street (street_name, isActive) values ('Golf', false);
insert into street (street_name, isActive) values ('Haas', false);
insert into street (street_name, isActive) values ('Troy', true);
insert into street (street_name, isActive) values ('Bellgrove', false);
insert into street (street_name, isActive) values ('Barby', true);
insert into street (street_name, isActive) values ('Forster', true);
insert into street (street_name, isActive) values ('Heffernan', false);
insert into street (street_name, isActive) values ('Corscot', false);
insert into street (street_name, isActive) values ('Fordem', true);
insert into street (street_name, isActive) values ('Eggendart', true);
insert into street (street_name, isActive) values ('Schurz', true);
insert into street (street_name, isActive) values ('Oneill', false);
insert into street (street_name, isActive) values ('Ilene', false);
insert into street (street_name, isActive) values ('Summerview', false);
insert into street (street_name, isActive) values ('Oakridge', true);
insert into street (street_name, isActive) values ('Duke', false);
insert into street (street_name, isActive) values ('Golden Leaf', false);
insert into street (street_name, isActive) values ('Knutson', true);
insert into street (street_name, isActive) values ('Golf', true);
insert into street (street_name, isActive) values ('Sundown', false);
insert into street (street_name, isActive) values ('Old Gate', false);
insert into street (street_name, isActive) values ('Kropf', false);
insert into street (street_name, isActive) values ('Bellgrove', false);
insert into street (street_name, isActive) values ('Hovde', false);
insert into street (street_name, isActive) values ('Northridge', false);
insert into street (street_name, isActive) values ('Barnett', true);
insert into street (street_name, isActive) values ('Hazelcrest', true);
insert into street (street_name, isActive) values ('Namekagon', true);
insert into street (street_name, isActive) values ('Stang', true);
insert into street (street_name, isActive) values ('Blackbird', true);
insert into street (street_name, isActive) values ('Weeping Birch', true);
insert into street (street_name, isActive) values ('Gateway', true);
insert into street (street_name, isActive) values ('La Follette', true);
insert into street (street_name, isActive) values ('Atwood', true);
insert into street (street_name, isActive) values ('Pleasure', true);
insert into street (street_name, isActive) values ('Victoria', true);
insert into street (street_name, isActive) values ('Carey', false);
insert into street (street_name, isActive) values ('Bashford', false);
insert into street (street_name, isActive) values ('Miller', false);
insert into street (street_name, isActive) values ('Blue Bill Park', false);
insert into street (street_name, isActive) values ('Leroy', true);
insert into street (street_name, isActive) values ('Kinsman', false);
insert into street (street_name, isActive) values ('Everett', true);
insert into street (street_name, isActive) values ('Heffernan', false);
insert into street (street_name, isActive) values ('Holy Cross', false);
insert into street (street_name, isActive) values ('Bonner', false);
insert into street (street_name, isActive) values ('Sachtjen', false);
insert into street (street_name, isActive) values ('Dixon', false);
insert into street (street_name, isActive) values ('Randy', false);
insert into street (street_name, isActive) values ('Monument', false);
insert into street (street_name, isActive) values ('Crowley', true);
insert into street (street_name, isActive) values ('West', false);
insert into street (street_name, isActive) values ('Nova', false);
insert into street (street_name, isActive) values ('Carpenter', true);
insert into street (street_name, isActive) values ('Kropf', false);
insert into street (street_name, isActive) values ('Grim', false);
insert into street (street_name, isActive) values ('Tony', false);
insert into street (street_name, isActive) values ('Garrison', true);
insert into street (street_name, isActive) values ('Service', true);
insert into street (street_name, isActive) values ('Autumn Leaf', false);
insert into street (street_name, isActive) values ('Ilene', true);
insert into street (street_name, isActive) values ('Killdeer', false);
insert into street (street_name, isActive) values ('Redwing', true);
insert into street (street_name, isActive) values ('La Follette', true);
insert into street (street_name, isActive) values ('Buhler', true);
insert into street (street_name, isActive) values ('Schlimgen', false);
insert into street (street_name, isActive) values ('Schmedeman', false);
insert into street (street_name, isActive) values ('Dahle', false);
insert into street (street_name, isActive) values ('Crescent Oaks', true);
insert into street (street_name, isActive) values ('Warner', false);
insert into street (street_name, isActive) values ('Memorial', true);
insert into street (street_name, isActive) values ('Ruskin', false);
insert into street (street_name, isActive) values ('Westend', false);
insert into street (street_name, isActive) values ('Dunning', true);
insert into street (street_name, isActive) values ('Utah', false);
insert into street (street_name, isActive) values ('Hooker', true);
insert into street (street_name, isActive) values ('Mandrake', true);
insert into street (street_name, isActive) values ('Toban', true);
insert into street (street_name, isActive) values ('Mallard', true);
insert into street (street_name, isActive) values ('Lindbergh', true);
insert into street (street_name, isActive) values ('Stuart', true);
insert into street (street_name, isActive) values ('Thackeray', false);
insert into street (street_name, isActive) values ('Roth', true);
insert into street (street_name, isActive) values ('Carberry', true);
insert into street (street_name, isActive) values ('Helena', true);
insert into street (street_name, isActive) values ('Towne', true);
insert into street (street_name, isActive) values ('Morning', true);
insert into street (street_name, isActive) values ('Trailsway', true);
insert into street (street_name, isActive) values ('Portage', false);
insert into street (street_name, isActive) values ('Gerald', true);
insert into street (street_name, isActive) values ('Alpine', true);
insert into street (street_name, isActive) values ('Scofield', true);
insert into street (street_name, isActive) values ('Memorial', true);
insert into street (street_name, isActive) values ('Green', false);
insert into street (street_name, isActive) values ('Hovde', true);
insert into street (street_name, isActive) values ('Ilene', true);
insert into street (street_name, isActive) values ('Manufacturers', false);
insert into street (street_name, isActive) values ('Northfield', false);
insert into street (street_name, isActive) values ('Monterey', false);
insert into street (street_name, isActive) values ('Tomscot', false);
insert into street (street_name, isActive) values ('Sheridan', true);
insert into street (street_name, isActive) values ('Ilene', true);
insert into street (street_name, isActive) values ('Texas', false);
insert into street (street_name, isActive) values ('Warbler', false);
insert into street (street_name, isActive) values ('Chive', false);
insert into street (street_name, isActive) values ('Truax', true);
insert into street (street_name, isActive) values ('Jenna', false);
insert into street (street_name, isActive) values ('Monterey', false);
insert into street (street_name, isActive) values ('Stone Corner', false);
insert into street (street_name, isActive) values ('Lotheville', true);
insert into street (street_name, isActive) values ('Brown', false);
insert into street (street_name, isActive) values ('Southridge', true);
insert into street (street_name, isActive) values ('Bobwhite', false);
insert into street (street_name, isActive) values ('Kings', true);
insert into street (street_name, isActive) values ('Talisman', false);
insert into street (street_name, isActive) values ('Spaight', true);
insert into street (street_name, isActive) values ('Prairieview', true);
insert into street (street_name, isActive) values ('Eggendart', true);
insert into street (street_name, isActive) values ('Sycamore', true);
insert into street (street_name, isActive) values ('Bultman', false);
insert into street (street_name, isActive) values ('Brown', true);
insert into street (street_name, isActive) values ('3rd', true);
insert into street (street_name, isActive) values ('John Wall', true);
insert into street (street_name, isActive) values ('2nd', true);
insert into street (street_name, isActive) values ('Park Meadow', false);
insert into street (street_name, isActive) values ('Stephen', false);
insert into street (street_name, isActive) values ('Hoffman', false);
insert into street (street_name, isActive) values ('Dakota', false);
insert into street (street_name, isActive) values ('Hanson', false);
insert into street (street_name, isActive) values ('Lotheville', false);
insert into street (street_name, isActive) values ('Mifflin', false);
insert into street (street_name, isActive) values ('Forster', true);
insert into street (street_name, isActive) values ('Anthes', false);
insert into street (street_name, isActive) values ('Coolidge', true);
insert into street (street_name, isActive) values ('Shelley', true);
insert into street (street_name, isActive) values ('Glacier Hill', false);
insert into street (street_name, isActive) values ('Gulseth', false);
insert into street (street_name, isActive) values ('Amoth', true);
insert into street (street_name, isActive) values ('Leroy', true);
insert into street (street_name, isActive) values ('Clyde Gallagher', false);
insert into street (street_name, isActive) values ('Bunting', false);
insert into street (street_name, isActive) values ('Warner', false);
insert into street (street_name, isActive) values ('Golf View', true);
insert into street (street_name, isActive) values ('Sycamore', false);
insert into street (street_name, isActive) values ('Hagan', false);
insert into street (street_name, isActive) values ('Fordem', false);
insert into street (street_name, isActive) values ('Bonner', true);
insert into street (street_name, isActive) values ('Melrose', false);
insert into street (street_name, isActive) values ('Fair Oaks', false);
insert into street (street_name, isActive) values ('Reinke', false);
insert into street (street_name, isActive) values ('Fordem', true);
insert into street (street_name, isActive) values ('Holmberg', true);
insert into street (street_name, isActive) values ('Superior', false);
insert into street (street_name, isActive) values ('Sage', false);
insert into street (street_name, isActive) values ('Manufacturers', true);
insert into street (street_name, isActive) values ('Spenser', true);
insert into street (street_name, isActive) values ('Steensland', false);
insert into street (street_name, isActive) values ('Annamark', false);
insert into street (street_name, isActive) values ('Debs', true);
insert into street (street_name, isActive) values ('Westerfield', true);
insert into street (street_name, isActive) values ('Novick', true);
insert into street (street_name, isActive) values ('Hayes', true);
insert into street (street_name, isActive) values ('Mayer', true);
insert into street (street_name, isActive) values ('International', false);
insert into street (street_name, isActive) values ('Dayton', true);
insert into street (street_name, isActive) values ('Blue Bill Park', false);
insert into street (street_name, isActive) values ('Heath', true);
insert into street (street_name, isActive) values ('Mesta', true);
insert into street (street_name, isActive) values ('Almo', true);
insert into street (street_name, isActive) values ('Magdeline', false);
insert into street (street_name, isActive) values ('Linden', true);
insert into street (street_name, isActive) values ('School', true);
insert into street (street_name, isActive) values ('Redwing', false);
insert into street (street_name, isActive) values ('Del Mar', true);
insert into street (street_name, isActive) values ('Glendale', false);
insert into street (street_name, isActive) values ('Dorton', false);
insert into street (street_name, isActive) values ('Shelley', true);
insert into street (street_name, isActive) values ('Steensland', false);
insert into street (street_name, isActive) values ('Russell', true);
insert into street (street_name, isActive) values ('John Wall', false);
insert into street (street_name, isActive) values ('Buena Vista', false);
insert into street (street_name, isActive) values ('Dapin', true);
insert into street (street_name, isActive) values ('6th', false);
insert into street (street_name, isActive) values ('Mandrake', true);
insert into street (street_name, isActive) values ('Carberry', false);
insert into street (street_name, isActive) values ('Ohio', false);
insert into street (street_name, isActive) values ('Duke', true);
insert into street (street_name, isActive) values ('Bluejay', false);
insert into street (street_name, isActive) values ('Ridgeview', true);
insert into street (street_name, isActive) values ('Sachs', false);
insert into street (street_name, isActive) values ('4th', false);
insert into street (street_name, isActive) values ('Golf Course', true);
insert into street (street_name, isActive) values ('Dexter', true);
insert into street (street_name, isActive) values ('Red Cloud', false);
insert into street (street_name, isActive) values ('Lerdahl', true);
insert into street (street_name, isActive) values ('Mockingbird', false);
insert into street (street_name, isActive) values ('Mayfield', true);
insert into street (street_name, isActive) values ('Knutson', true);
insert into street (street_name, isActive) values ('Summerview', false);
insert into street (street_name, isActive) values ('Carberry', false);
insert into street (street_name, isActive) values ('Colorado', true);
insert into street (street_name, isActive) values ('Springview', true);
insert into street (street_name, isActive) values ('Westend', true);
insert into street (street_name, isActive) values ('Badeau', true);
insert into street (street_name, isActive) values ('Oxford', true);
insert into street (street_name, isActive) values ('Lakeland', false);
insert into street (street_name, isActive) values ('Sundown', false);
insert into street (street_name, isActive) values ('Weeping Birch', false);
insert into street (street_name, isActive) values ('Kinsman', true);
insert into street (street_name, isActive) values ('Reinke', false);
insert into street (street_name, isActive) values ('Kipling', true);
insert into street (street_name, isActive) values ('Del Mar', false);
insert into street (street_name, isActive) values ('Green', true);
insert into street (street_name, isActive) values ('Canary', false);
insert into street (street_name, isActive) values ('Moland', true);
insert into street (street_name, isActive) values ('Cherokee', false);
insert into street (street_name, isActive) values ('Fairview', false);
insert into street (street_name, isActive) values ('Rusk', true);
insert into street (street_name, isActive) values ('Lakewood Gardens', true);
insert into street (street_name, isActive) values ('Mockingbird', true);
insert into street (street_name, isActive) values ('Northfield', false);
insert into street (street_name, isActive) values ('Orin', true);
insert into street (street_name, isActive) values ('Hoffman', true);
insert into street (street_name, isActive) values ('Crowley', true);
insert into street (street_name, isActive) values ('Oriole', true);
insert into street (street_name, isActive) values ('Lyons', true);
insert into street (street_name, isActive) values ('6th', false);
insert into street (street_name, isActive) values ('Sachtjen', true);
insert into street (street_name, isActive) values ('Elmside', true);
insert into street (street_name, isActive) values ('Dennis', true);
insert into street (street_name, isActive) values ('Morrow', false);
insert into street (street_name, isActive) values ('Lunder', false);
insert into street (street_name, isActive) values ('Parkside', true);
insert into street (street_name, isActive) values ('Ohio', false);
insert into street (street_name, isActive) values ('Nancy', true);
insert into street (street_name, isActive) values ('Dennis', false);
insert into street (street_name, isActive) values ('Grover', true);
insert into street (street_name, isActive) values ('Dixon', false);
insert into street (street_name, isActive) values ('Vermont', true);
insert into street (street_name, isActive) values ('Stang', false);
insert into street (street_name, isActive) values ('Melrose', true);
insert into street (street_name, isActive) values ('Swallow', true);
insert into street (street_name, isActive) values ('Glendale', true);
insert into street (street_name, isActive) values ('Sunnyside', false);
insert into street (street_name, isActive) values ('Grover', false);
insert into street (street_name, isActive) values ('Schurz', true);
insert into street (street_name, isActive) values ('Amoth', false);
insert into street (street_name, isActive) values ('Sherman', false);
insert into street (street_name, isActive) values ('Corben', false);
insert into street (street_name, isActive) values ('Nevada', true);
insert into street (street_name, isActive) values ('Everett', false);
insert into street (street_name, isActive) values ('Morningstar', true);
insert into street (street_name, isActive) values ('Forster', true);
insert into street (street_name, isActive) values ('Manley', false);
insert into street (street_name, isActive) values ('Coolidge', true);
insert into street (street_name, isActive) values ('Thackeray', false);
insert into street (street_name, isActive) values ('Cambridge', false);
insert into street (street_name, isActive) values ('Swallow', false);
insert into street (street_name, isActive) values ('Sutherland', true);
insert into street (street_name, isActive) values ('Pierstorff', true);
insert into street (street_name, isActive) values ('School', true);
insert into street (street_name, isActive) values ('Cascade', false);
insert into street (street_name, isActive) values ('Petterle', true);
insert into street (street_name, isActive) values ('Stang', false);
insert into street (street_name, isActive) values ('Gale', false);
insert into street (street_name, isActive) values ('Briar Crest', false);
insert into street (street_name, isActive) values ('Sullivan', true);
insert into street (street_name, isActive) values ('Anniversary', false);
insert into street (street_name, isActive) values ('Swallow', false);
insert into street (street_name, isActive) values ('Lukken', false);
insert into street (street_name, isActive) values ('Rigney', false);
insert into street (street_name, isActive) values ('Holmberg', false);
insert into street (street_name, isActive) values ('Lakewood', false);
insert into street (street_name, isActive) values ('Dayton', false);
insert into street (street_name, isActive) values ('Grim', true);
insert into street (street_name, isActive) values ('Vidon', true);
insert into street (street_name, isActive) values ('Graceland', true);
insert into street (street_name, isActive) values ('Oak Valley', true);
insert into street (street_name, isActive) values ('Bobwhite', true);
insert into street (street_name, isActive) values ('Warrior', true);
insert into street (street_name, isActive) values ('1st', true);
insert into street (street_name, isActive) values ('Esch', true);
insert into street (street_name, isActive) values ('Merrick', false);
insert into street (street_name, isActive) values ('Sullivan', true);
insert into street (street_name, isActive) values ('David', false);
insert into street (street_name, isActive) values ('Clyde Gallagher', false);
insert into street (street_name, isActive) values ('Northland', false);
insert into street (street_name, isActive) values ('Northridge', true);
insert into street (street_name, isActive) values ('Cody', false);
insert into street (street_name, isActive) values ('Blackbird', false);
insert into street (street_name, isActive) values ('Oak Valley', true);
insert into street (street_name, isActive) values ('Eagle Crest', true);
insert into street (street_name, isActive) values ('Schiller', false);
insert into street (street_name, isActive) values ('Anthes', true);
insert into street (street_name, isActive) values ('Union', true);
insert into street (street_name, isActive) values ('Hollow Ridge', true);
insert into street (street_name, isActive) values ('Golden Leaf', false);
insert into street (street_name, isActive) values ('Huxley', true);
insert into street (street_name, isActive) values ('Warrior', false);
insert into street (street_name, isActive) values ('Brown', true);
insert into street (street_name, isActive) values ('Elka', false);
insert into street (street_name, isActive) values ('Dunning', true);
insert into street (street_name, isActive) values ('Kingsford', true);
insert into street (street_name, isActive) values ('5th', false);
insert into street (street_name, isActive) values ('Rieder', false);
insert into street (street_name, isActive) values ('Eliot', true);
insert into street (street_name, isActive) values ('Rockefeller', false);
insert into street (street_name, isActive) values ('Del Mar', true);
insert into street (street_name, isActive) values ('Memorial', true);
insert into street (street_name, isActive) values ('Village', true);
insert into street (street_name, isActive) values ('Walton', false);
insert into street (street_name, isActive) values ('Knutson', false);
insert into street (street_name, isActive) values ('Havey', false);
insert into street (street_name, isActive) values ('Crescent Oaks', false);
insert into street (street_name, isActive) values ('Boyd', true);
insert into street (street_name, isActive) values ('Reindahl', false);
insert into street (street_name, isActive) values ('Arapahoe', true);
insert into street (street_name, isActive) values ('Toban', true);
insert into street (street_name, isActive) values ('Hayes', false);
insert into street (street_name, isActive) values ('Memorial', true);
insert into street (street_name, isActive) values ('Gina', false);
insert into street (street_name, isActive) values ('Hoepker', false);
insert into street (street_name, isActive) values ('Vahlen', false);
insert into street (street_name, isActive) values ('Glacier Hill', false);
insert into street (street_name, isActive) values ('Warner', true);
insert into street (street_name, isActive) values ('Hanson', false);
insert into street (street_name, isActive) values ('Kinsman', true);
insert into street (street_name, isActive) values ('Sauthoff', true);
insert into street (street_name, isActive) values ('Buell', false);
insert into street (street_name, isActive) values ('Beilfuss', true);
insert into street (street_name, isActive) values ('Shasta', true);
insert into street (street_name, isActive) values ('Thackeray', false);
insert into street (street_name, isActive) values ('Sloan', true);
insert into street (street_name, isActive) values ('Crest Line', true);
insert into street (street_name, isActive) values ('Nelson', true);
insert into street (street_name, isActive) values ('Mesta', true);
insert into street (street_name, isActive) values ('Randy', true);
insert into street (street_name, isActive) values ('Veith', true);
insert into street (street_name, isActive) values ('Maple', false);
insert into street (street_name, isActive) values ('Ryan', false);
insert into street (street_name, isActive) values ('Mallard', false);
insert into street (street_name, isActive) values ('Packers', false);
insert into street (street_name, isActive) values ('Florence', false);
insert into street (street_name, isActive) values ('Twin Pines', true);
insert into street (street_name, isActive) values ('Duke', false);
insert into street (street_name, isActive) values ('Thompson', true);
insert into street (street_name, isActive) values ('Hanover', false);
insert into street (street_name, isActive) values ('Farmco', false);
insert into street (street_name, isActive) values ('Almo', true);
insert into street (street_name, isActive) values ('Delaware', false);
insert into street (street_name, isActive) values ('Pearson', false);
insert into street (street_name, isActive) values ('Caliangt', false);
insert into street (street_name, isActive) values ('Banding', false);
insert into street (street_name, isActive) values ('Briar Crest', false);
insert into street (street_name, isActive) values ('Charing Cross', false);
insert into street (street_name, isActive) values ('Village Green', false);
insert into street (street_name, isActive) values ('Kim', false);
insert into street (street_name, isActive) values ('Kedzie', true);
insert into street (street_name, isActive) values ('Tennyson', true);
insert into street (street_name, isActive) values ('Myrtle', true);
insert into street (street_name, isActive) values ('Sachs', false);
insert into street (street_name, isActive) values ('Dahle', false);
insert into street (street_name, isActive) values ('Jenna', false);
insert into street (street_name, isActive) values ('Jay', true);
insert into street (street_name, isActive) values ('Petterle', false);
insert into street (street_name, isActive) values ('Mitchell', true);
insert into street (street_name, isActive) values ('Jenna', false);
insert into street (street_name, isActive) values ('Merrick', true);
insert into street (street_name, isActive) values ('Oriole', false);
insert into street (street_name, isActive) values ('Boyd', true);
insert into street (street_name, isActive) values ('Sunfield', true);
insert into street (street_name, isActive) values ('Welch', false);
insert into street (street_name, isActive) values ('Atwood', true);
insert into street (street_name, isActive) values ('Meadow Valley', false);
insert into street (street_name, isActive) values ('Anzinger', true);
insert into street (street_name, isActive) values ('Scofield', true);
insert into street (street_name, isActive) values ('Algoma', false);
insert into street (street_name, isActive) values ('Goodland', false);
insert into street (street_name, isActive) values ('Northview', true);
insert into street (street_name, isActive) values ('Westend', false);
insert into street (street_name, isActive) values ('Ohio', true);
insert into street (street_name, isActive) values ('Debra', true);
insert into street (street_name, isActive) values ('Straubel', false);
insert into street (street_name, isActive) values ('Esker', false);
insert into street (street_name, isActive) values ('Nevada', true);
insert into street (street_name, isActive) values ('Michigan', false);
insert into street (street_name, isActive) values ('8th', false);
insert into street (street_name, isActive) values ('Canary', true);
insert into street (street_name, isActive) values ('Heath', false);
insert into street (street_name, isActive) values ('Stephen', true);
insert into street (street_name, isActive) values ('West', false);
insert into street (street_name, isActive) values ('Packers', false);
insert into street (street_name, isActive) values ('Thompson', false);
insert into street (street_name, isActive) values ('Londonderry', true);
insert into street (street_name, isActive) values ('Sherman', true);
insert into street (street_name, isActive) values ('Prairieview', true);
insert into street (street_name, isActive) values ('Lake View', true);
insert into street (street_name, isActive) values ('John Wall', false);
insert into street (street_name, isActive) values ('Lotheville', true);
insert into street (street_name, isActive) values ('7th', true);
insert into street (street_name, isActive) values ('Sycamore', false);
insert into street (street_name, isActive) values ('Hovde', true);
insert into street (street_name, isActive) values ('Comanche', false);
insert into street (street_name, isActive) values ('Parkside', true);
insert into street (street_name, isActive) values ('Porter', true);
insert into street (street_name, isActive) values ('New Castle', false);
insert into street (street_name, isActive) values ('Vidon', false);
insert into street (street_name, isActive) values ('Kingsford', false);
insert into street (street_name, isActive) values ('Mendota', true);
insert into street (street_name, isActive) values ('Loomis', true);
insert into street (street_name, isActive) values ('Buhler', true);
insert into street (street_name, isActive) values ('Melrose', false);
insert into street (street_name, isActive) values ('Washington', true);
insert into street (street_name, isActive) values ('Erie', true);
insert into street (street_name, isActive) values ('Prentice', true);
insert into street (street_name, isActive) values ('Goodland', true);
insert into street (street_name, isActive) values ('Evergreen', true);
insert into street (street_name, isActive) values ('Graedel', false);
insert into street (street_name, isActive) values ('Sommers', true);
insert into street (street_name, isActive) values ('Holmberg', true);
insert into street (street_name, isActive) values ('Hovde', false);
insert into street (street_name, isActive) values ('Esch', false);
insert into street (street_name, isActive) values ('Lotheville', true);
insert into street (street_name, isActive) values ('Arkansas', false);
insert into street (street_name, isActive) values ('Bluejay', true);
insert into street (street_name, isActive) values ('Sutherland', true);
insert into street (street_name, isActive) values ('Raven', false);
insert into street (street_name, isActive) values ('Bluestem', true);
insert into street (street_name, isActive) values ('Fairview', false);
insert into street (street_name, isActive) values ('Coleman', false);
insert into street (street_name, isActive) values ('Macpherson', false);
insert into street (street_name, isActive) values ('Northridge', true);
insert into street (street_name, isActive) values ('Fisk', false);
insert into street (street_name, isActive) values ('Susan', true);
insert into street (street_name, isActive) values ('Hermina', false);
insert into street (street_name, isActive) values ('Buhler', true);
insert into street (street_name, isActive) values ('Hooker', true);
insert into street (street_name, isActive) values ('Elka', true);
insert into street (street_name, isActive) values ('Sheridan', true);
insert into street (street_name, isActive) values ('Golf View', true);
insert into street (street_name, isActive) values ('Bluestem', true);
insert into street (street_name, isActive) values ('Debs', true);
insert into street (street_name, isActive) values ('Prairie Rose', false);
insert into street (street_name, isActive) values ('Talmadge', false);
insert into street (street_name, isActive) values ('Granby', true);
insert into street (street_name, isActive) values ('Jackson', false);
insert into street (street_name, isActive) values ('International', true);
insert into street (street_name, isActive) values ('Coolidge', true);
insert into street (street_name, isActive) values ('Sauthoff', false);
insert into street (street_name, isActive) values ('Oriole', false);
insert into street (street_name, isActive) values ('Memorial', false);
insert into street (street_name, isActive) values ('Nelson', false);
insert into street (street_name, isActive) values ('Montana', true);
insert into street (street_name, isActive) values ('Weeping Birch', false);
insert into street (street_name, isActive) values ('Katie', true);
insert into street (street_name, isActive) values ('Di Loreto', true);
insert into street (street_name, isActive) values ('Amoth', false);
insert into street (street_name, isActive) values ('Larry', false);
insert into street (street_name, isActive) values ('Kinsman', true);
insert into street (street_name, isActive) values ('Bayside', true);
insert into street (street_name, isActive) values ('Evergreen', true);
insert into street (street_name, isActive) values ('Hooker', false);
insert into street (street_name, isActive) values ('Farmco', true);
insert into street (street_name, isActive) values ('Everett', true);
insert into street (street_name, isActive) values ('Melody', false);
insert into street (street_name, isActive) values ('Di Loreto', true);
insert into street (street_name, isActive) values ('Center', false);
insert into street (street_name, isActive) values ('Bartillon', false);
insert into street (street_name, isActive) values ('Hagan', true);
insert into street (street_name, isActive) values ('Londonderry', false);
insert into street (street_name, isActive) values ('Stephen', false);
insert into street (street_name, isActive) values ('Bonner', false);
insert into street (street_name, isActive) values ('American Ash', true);
insert into street (street_name, isActive) values ('Northland', false);
insert into street (street_name, isActive) values ('Harper', true);
insert into street (street_name, isActive) values ('Hoffman', true);
insert into street (street_name, isActive) values ('Burrows', true);
insert into street (street_name, isActive) values ('Artisan', false);
insert into street (street_name, isActive) values ('Pierstorff', false);
insert into street (street_name, isActive) values ('Loeprich', true);
insert into street (street_name, isActive) values ('Northwestern', true);
insert into street (street_name, isActive) values ('Kedzie', false);
insert into street (street_name, isActive) values ('Mitchell', false);
insert into street (street_name, isActive) values ('Graceland', false);
insert into street (street_name, isActive) values ('Hayes', false);
insert into street (street_name, isActive) values ('Stoughton', true);
insert into street (street_name, isActive) values ('Fulton', true);
insert into street (street_name, isActive) values ('Miller', true);
insert into street (street_name, isActive) values ('Blackbird', false);
insert into street (street_name, isActive) values ('Saint Paul', true);
insert into street (street_name, isActive) values ('Brickson Park', true);
insert into street (street_name, isActive) values ('Swallow', true);
insert into street (street_name, isActive) values ('Debs', true);
insert into street (street_name, isActive) values ('Onsgard', true);
insert into street (street_name, isActive) values ('Vera', false);
insert into street (street_name, isActive) values ('Pine View', true);
insert into street (street_name, isActive) values ('Luster', false);
insert into street (street_name, isActive) values ('Bayside', true);
insert into street (street_name, isActive) values ('Heath', true);
insert into street (street_name, isActive) values ('Dennis', false);
insert into street (street_name, isActive) values ('Green', true);
insert into street (street_name, isActive) values ('Scott', true);
insert into street (street_name, isActive) values ('Fulton', false);
insert into street (street_name, isActive) values ('Eagle Crest', true);
insert into street (street_name, isActive) values ('Brickson Park', false);
insert into street (street_name, isActive) values ('Dapin', true);
insert into street (street_name, isActive) values ('Dexter', false);
insert into street (street_name, isActive) values ('Transport', false);
insert into street (street_name, isActive) values ('Union', true);
insert into street (street_name, isActive) values ('Hermina', false);
insert into street (street_name, isActive) values ('Dottie', false);
insert into street (street_name, isActive) values ('Vahlen', false);
insert into street (street_name, isActive) values ('Arrowood', true);
insert into street (street_name, isActive) values ('Anzinger', true);
insert into street (street_name, isActive) values ('Center', false);
insert into street (street_name, isActive) values ('Comanche', false);
insert into street (street_name, isActive) values ('Summerview', false);
insert into street (street_name, isActive) values ('Everett', false);
insert into street (street_name, isActive) values ('International', true);
insert into street (street_name, isActive) values ('Hanson', false);
insert into street (street_name, isActive) values ('Warrior', false);
insert into street (street_name, isActive) values ('Dwight', false);
insert into street (street_name, isActive) values ('Monterey', false);
insert into street (street_name, isActive) values ('Corben', true);
insert into street (street_name, isActive) values ('Killdeer', true);
insert into street (street_name, isActive) values ('Ryan', true);
insert into street (street_name, isActive) values ('Mandrake', false);
insert into street (street_name, isActive) values ('Monica', true);
insert into street (street_name, isActive) values ('Morning', false);
insert into street (street_name, isActive) values ('Parkside', true);
insert into street (street_name, isActive) values ('Pennsylvania', false);
insert into street (street_name, isActive) values ('Portage', false);
insert into street (street_name, isActive) values ('Porter', false);
insert into street (street_name, isActive) values ('Hollow Ridge', false);
insert into street (street_name, isActive) values ('West', false);
insert into street (street_name, isActive) values ('Evergreen', true);
insert into street (street_name, isActive) values ('Schlimgen', true);
insert into street (street_name, isActive) values ('Hollow Ridge', true);
insert into street (street_name, isActive) values ('Springs', false);
insert into street (street_name, isActive) values ('Loomis', false);
insert into street (street_name, isActive) values ('Nancy', true);
insert into street (street_name, isActive) values ('Northridge', true);
insert into street (street_name, isActive) values ('Dryden', true);
insert into street (street_name, isActive) values ('Mitchell', true);
insert into street (street_name, isActive) values ('Troy', true);
insert into street (street_name, isActive) values ('Di Loreto', false);
insert into street (street_name, isActive) values ('Debs', false);
insert into street (street_name, isActive) values ('Canary', false);
insert into street (street_name, isActive) values ('Morning', false);
insert into street (street_name, isActive) values ('Graedel', false);
insert into street (street_name, isActive) values ('Waubesa', true);
insert into street (street_name, isActive) values ('Rigney', false);
insert into street (street_name, isActive) values ('Hansons', true);
insert into street (street_name, isActive) values ('Golden Leaf', true);
insert into street (street_name, isActive) values ('Texas', false);
insert into street (street_name, isActive) values ('Erie', false);
insert into street (street_name, isActive) values ('Sachs', false);
insert into street (street_name, isActive) values ('Dahle', false);
insert into street (street_name, isActive) values ('Westridge', false);
insert into street (street_name, isActive) values ('Ohio', true);
insert into street (street_name, isActive) values ('Eggendart', false);
insert into street (street_name, isActive) values ('Corben', false);
insert into street (street_name, isActive) values ('Fairfield', true);
insert into street (street_name, isActive) values ('Summit', false);
insert into street (street_name, isActive) values ('Alpine', false);
insert into street (street_name, isActive) values ('Warner', false);
insert into street (street_name, isActive) values ('Nevada', true);
insert into street (street_name, isActive) values ('Declaration', true);
insert into street (street_name, isActive) values ('Carey', false);
insert into street (street_name, isActive) values ('Northport', false);
insert into street (street_name, isActive) values ('2nd', true);
insert into street (street_name, isActive) values ('Sheridan', false);
insert into street (street_name, isActive) values ('Tennyson', true);
insert into street (street_name, isActive) values ('Hagan', false);
insert into street (street_name, isActive) values ('Prentice', true);
insert into street (street_name, isActive) values ('Everett', true);
insert into street (street_name, isActive) values ('Dawn', false);
insert into street (street_name, isActive) values ('Debra', false);
insert into street (street_name, isActive) values ('School', true);
insert into street (street_name, isActive) values ('Pleasure', false);
insert into street (street_name, isActive) values ('Green', true);
insert into street (street_name, isActive) values ('Daystar', false);
insert into street (street_name, isActive) values ('Union', true);
insert into street (street_name, isActive) values ('Kingsford', false);
insert into street (street_name, isActive) values ('Redwing', false);
insert into street (street_name, isActive) values ('Bayside', true);
insert into street (street_name, isActive) values ('Sycamore', true);
insert into street (street_name, isActive) values ('Banding', false);
insert into street (street_name, isActive) values ('Pepper Wood', true);
insert into street (street_name, isActive) values ('Derek', false);
insert into street (street_name, isActive) values ('Grasskamp', false);
insert into street (street_name, isActive) values ('Mosinee', false);
insert into street (street_name, isActive) values ('Hudson', false);
insert into street (street_name, isActive) values ('Cordelia', false);
insert into street (street_name, isActive) values ('Carberry', true);
insert into street (street_name, isActive) values ('Thompson', true);
insert into street (street_name, isActive) values ('Montana', false);
insert into street (street_name, isActive) values ('Alpine', false);
insert into street (street_name, isActive) values ('West', true);
insert into street (street_name, isActive) values ('Paget', false);
insert into street (street_name, isActive) values ('Miller', true);
insert into street (street_name, isActive) values ('Weeping Birch', false);
insert into street (street_name, isActive) values ('Hansons', false);
insert into street (street_name, isActive) values ('Rowland', true);
insert into street (street_name, isActive) values ('Dunning', true);
insert into street (street_name, isActive) values ('Columbus', false);
insert into street (street_name, isActive) values ('Melby', true);
insert into street (street_name, isActive) values ('Moulton', true);
insert into street (street_name, isActive) values ('School', false);
insert into street (street_name, isActive) values ('North', true);
insert into street (street_name, isActive) values ('Sage', true);
insert into street (street_name, isActive) values ('Amoth', true);
insert into street (street_name, isActive) values ('Barnett', true);
insert into street (street_name, isActive) values ('Tony', false);
insert into street (street_name, isActive) values ('Talisman', false);
insert into street (street_name, isActive) values ('Quincy', true);
insert into street (street_name, isActive) values ('Eliot', false);
insert into street (street_name, isActive) values ('Aberg', true);
insert into street (street_name, isActive) values ('Loeprich', false);
insert into street (street_name, isActive) values ('Reinke', false);
insert into street (street_name, isActive) values ('Eastwood', false);
insert into street (street_name, isActive) values ('Cordelia', true);
insert into street (street_name, isActive) values ('Gale', true);
insert into street (street_name, isActive) values ('1st', false);
insert into street (street_name, isActive) values ('6th', true);
insert into street (street_name, isActive) values ('Sloan', false);
insert into street (street_name, isActive) values ('Elka', true);
insert into street (street_name, isActive) values ('Sullivan', false);
insert into street (street_name, isActive) values ('Commercial', true);
insert into street (street_name, isActive) values ('Florence', true);
insert into street (street_name, isActive) values ('Village', false);
insert into street (street_name, isActive) values ('Dovetail', true);
insert into street (street_name, isActive) values ('Lakewood', true);
insert into street (street_name, isActive) values ('Summer Ridge', false);
insert into street (street_name, isActive) values ('Waywood', false);
insert into street (street_name, isActive) values ('Glendale', true);
insert into street (street_name, isActive) values ('Fordem', true);
insert into street (street_name, isActive) values ('Dorton', true);
insert into street (street_name, isActive) values ('Springs', false);
insert into street (street_name, isActive) values ('Ridgeway', true);
insert into street (street_name, isActive) values ('Lillian', true);
insert into street (street_name, isActive) values ('Summerview', true);
insert into street (street_name, isActive) values ('Boyd', false);
insert into street (street_name, isActive) values ('Grover', false);
insert into street (street_name, isActive) values ('Summer Ridge', true);
insert into street (street_name, isActive) values ('Shopko', false);
insert into street (street_name, isActive) values ('Westend', true);
insert into street (street_name, isActive) values ('Farmco', true);
insert into street (street_name, isActive) values ('Gerald', false);
insert into street (street_name, isActive) values ('Sutteridge', true);
insert into street (street_name, isActive) values ('Nova', true);
insert into street (street_name, isActive) values ('Carpenter', false);
insert into street (street_name, isActive) values ('Sunnyside', false);
insert into street (street_name, isActive) values ('Talmadge', false);
insert into street (street_name, isActive) values ('Bluejay', false);
insert into street (street_name, isActive) values ('Riverside', true);
insert into street (street_name, isActive) values ('Dennis', false);
insert into street (street_name, isActive) values ('Lakeland', false);
insert into street (street_name, isActive) values ('Division', false);
insert into street (street_name, isActive) values ('Brentwood', true);
insert into street (street_name, isActive) values ('Lawn', true);
insert into street (street_name, isActive) values ('Kenwood', true);
insert into street (street_name, isActive) values ('Waywood', false);
insert into street (street_name, isActive) values ('Ridge Oak', true);
insert into street (street_name, isActive) values ('Dunning', true);
insert into street (street_name, isActive) values ('Burrows', true);
insert into street (street_name, isActive) values ('8th', false);
insert into street (street_name, isActive) values ('Schmedeman', true);
insert into street (street_name, isActive) values ('Declaration', false);
insert into street (street_name, isActive) values ('Buell', false);
insert into street (street_name, isActive) values ('Ridgeway', false);
insert into street (street_name, isActive) values ('Red Cloud', true);
insert into street (street_name, isActive) values ('Stuart', false);
insert into street (street_name, isActive) values ('Hoard', false);
insert into street (street_name, isActive) values ('Boyd', true);
insert into street (street_name, isActive) values ('Mayfield', true);
insert into street (street_name, isActive) values ('Del Sol', true);
insert into street (street_name, isActive) values ('Buena Vista', true);
insert into street (street_name, isActive) values ('Drewry', false);
insert into street (street_name, isActive) values ('Sullivan', false);
insert into street (street_name, isActive) values ('Aberg', true);
insert into street (street_name, isActive) values ('Anzinger', true);
insert into street (street_name, isActive) values ('Bashford', true);
insert into street (street_name, isActive) values ('Express', true);
insert into street (street_name, isActive) values ('Eliot', false);
insert into street (street_name, isActive) values ('Scoville', true);
insert into street (street_name, isActive) values ('Jay', true);
insert into street (street_name, isActive) values ('Ronald Regan', false);
insert into street (street_name, isActive) values ('Harbort', true);
insert into street (street_name, isActive) values ('Anzinger', true);
insert into street (street_name, isActive) values ('Butternut', true);
insert into street (street_name, isActive) values ('Dryden', false);
insert into street (street_name, isActive) values ('Old Gate', true);
insert into street (street_name, isActive) values ('Acker', false);
insert into street (street_name, isActive) values ('School', true);
insert into street (street_name, isActive) values ('Dovetail', false);
insert into street (street_name, isActive) values ('Corscot', false);
insert into street (street_name, isActive) values ('Merry', true);
insert into street (street_name, isActive) values ('Portage', false);
insert into street (street_name, isActive) values ('Blackbird', false);
insert into street (street_name, isActive) values ('Montana', true);
insert into street (street_name, isActive) values ('Almo', true);
insert into street (street_name, isActive) values ('Rieder', true);
insert into street (street_name, isActive) values ('Huxley', true);
insert into street (street_name, isActive) values ('Nobel', true);
insert into street (street_name, isActive) values ('South', true);
insert into street (street_name, isActive) values ('Aberg', true);
insert into street (street_name, isActive) values ('Carioca', false);
insert into street (street_name, isActive) values ('6th', false);
insert into street (street_name, isActive) values ('Clarendon', false);
insert into street (street_name, isActive) values ('Cambridge', false);
insert into street (street_name, isActive) values ('Merrick', false);
insert into street (street_name, isActive) values ('Morning', false);
insert into street (street_name, isActive) values ('Milwaukee', false);
insert into street (street_name, isActive) values ('Lien', true);
insert into street (street_name, isActive) values ('Paget', true);
insert into street (street_name, isActive) values ('Rockefeller', true);
insert into street (street_name, isActive) values ('Heath', true);
insert into street (street_name, isActive) values ('Sachtjen', false);
insert into street (street_name, isActive) values ('Dwight', true);
insert into street (street_name, isActive) values ('Petterle', true);
insert into street (street_name, isActive) values ('Sugar', true);
insert into street (street_name, isActive) values ('Mcguire', true);
insert into street (street_name, isActive) values ('Florence', true);
insert into street (street_name, isActive) values ('Monument', true);
insert into street (street_name, isActive) values ('Lunder', false);
insert into street (street_name, isActive) values ('Spohn', true);
insert into street (street_name, isActive) values ('Elka', false);
insert into street (street_name, isActive) values ('Pleasure', false);
insert into street (street_name, isActive) values ('Fairfield', true);
insert into street (street_name, isActive) values ('Butterfield', true);
insert into street (street_name, isActive) values ('Green Ridge', true);
insert into street (street_name, isActive) values ('Ronald Regan', true);
insert into street (street_name, isActive) values ('Sommers', true);
insert into street (street_name, isActive) values ('Pearson', true);
insert into street (street_name, isActive) values ('Graceland', true);
insert into street (street_name, isActive) values ('La Follette', true);
insert into street (street_name, isActive) values ('Schurz', true);
insert into street (street_name, isActive) values ('Mockingbird', true);
insert into street (street_name, isActive) values ('Dovetail', false);
insert into street (street_name, isActive) values ('Elmside', true);
insert into street (street_name, isActive) values ('Sutteridge', true);
insert into street (street_name, isActive) values ('Springs', false);
insert into street (street_name, isActive) values ('Susan', false);
insert into street (street_name, isActive) values ('Sommers', true);
insert into street (street_name, isActive) values ('Declaration', false);
insert into street (street_name, isActive) values ('Sundown', true);
insert into street (street_name, isActive) values ('Tennyson', true);
insert into street (street_name, isActive) values ('Harbort', true);
insert into street (street_name, isActive) values ('Di Loreto', true);
insert into street (street_name, isActive) values ('Corry', true);
insert into street (street_name, isActive) values ('Fordem', false);
insert into street (street_name, isActive) values ('Brickson Park', false);
insert into street (street_name, isActive) values ('Beilfuss', false);
insert into street (street_name, isActive) values ('Brown', true);
insert into street (street_name, isActive) values ('Veith', true);
insert into street (street_name, isActive) values ('Reinke', false);
insert into street (street_name, isActive) values ('Hansons', false);
insert into street (street_name, isActive) values ('Anniversary', false);
insert into street (street_name, isActive) values ('Starling', false);
insert into street (street_name, isActive) values ('Saint Paul', true);
insert into street (street_name, isActive) values ('Hanson', false);
insert into street (street_name, isActive) values ('Glendale', false);
insert into street (street_name, isActive) values ('Fisk', false);
insert into street (street_name, isActive) values ('Meadow Vale', true);
insert into street (street_name, isActive) values ('Grayhawk', false);
insert into street (street_name, isActive) values ('Troy', false);
insert into street (street_name, isActive) values ('Colorado', true);
insert into street (street_name, isActive) values ('Golf Course', true);
insert into street (street_name, isActive) values ('Red Cloud', false);
insert into street (street_name, isActive) values ('Westerfield', false);
insert into street (street_name, isActive) values ('Northport', false);
insert into street (street_name, isActive) values ('Cascade', true);
insert into street (street_name, isActive) values ('Manley', false);
insert into street (street_name, isActive) values ('Londonderry', true);
insert into street (street_name, isActive) values ('Waxwing', true);
insert into street (street_name, isActive) values ('Garrison', false);
insert into street (street_name, isActive) values ('Eagan', false);
insert into street (street_name, isActive) values ('Blue Bill Park', false);
insert into street (street_name, isActive) values ('Marcy', true);
insert into street (street_name, isActive) values ('Lyons', true);
insert into street (street_name, isActive) values ('8th', false);
insert into street (street_name, isActive) values ('Acker', false);
insert into street (street_name, isActive) values ('Ridge Oak', false);
insert into street (street_name, isActive) values ('Green', true);
insert into street (street_name, isActive) values ('Del Sol', false);
insert into street (street_name, isActive) values ('Scott', false);
insert into street (street_name, isActive) values ('Maple Wood', true);
insert into street (street_name, isActive) values ('Acker', true);
insert into street (street_name, isActive) values ('6th', false);
insert into street (street_name, isActive) values ('Red Cloud', true);
insert into street (street_name, isActive) values ('Surrey', false);
insert into street (street_name, isActive) values ('Donald', false);
