INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('1 kg pkg.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 - 200 g glasses', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 - 4 oz boxes', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 - 500 g pkgs.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 boxes x 12 pieces', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 boxes x 20 bags', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 boxes x 8 pieces', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 kg pkg.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('10 pkgs.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('100 - 100 g pieces', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('100 - 250 g bags', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 1 lb pkgs.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 100 g bars', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 100 g pkgs', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 12 oz cans', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 12 oz jars.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 200 ml jars', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 250 g pkgs.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 355 ml cans', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 500 g pkgs.', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 550 ml bottles', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 75 cl bottles', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 - 8 oz jars', true);
INSERT INTO grp24.weight_unit (weight_unit_name, isActive) VALUES ('12 boxes', true);